### ISSUE TITLE
Olvashato valtozonevek es java konvencios interface-ek

### ISSUE THREAD

**Issue by davidstvn** [BME-MIT-IET/iet-hf-2024-team-bober#2]
A jatekban kiirt valtozonevek ne legyenek roviditve, peldaul a mezok, amikre lepni lehet, ne ilyenek legyenek: L1, L2, IL1, W1, F8. Az attack-nal ne legyen 2 darab V1, mert ez nem egyertelmu vagy ez egy hiba. A java interface-ek kovessek a java konvenciokat, ne legyen a nevuk IValami.java.

**Comment by Tamassch** [comment]
Módosítottam a map1-et egyszerűek lettek az elnevezések, most már felhasználó szempontjából jobb az elményt.
